sudo: required

language: generic 

services:
  - docker

before_install:
  - docker build -t serhii/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true serhii/docker-react npm run test

  deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-react"
    env: "DockerReact-env-1"
    bucket_name: "elasticbeanstalk-us-east-2-832459988545"
    bucket_path: "docker-react"
    on: 
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
